name: Auto Crawl & Clean Data

on:
  schedule:
    - cron:  '0 11 * * *'
  workflow_dispatch:

jobs:
  crawl-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          

      - name: Crawl links
        run: python BATCH/VNWscraping/Crawl_link.py

      - name: Commit _links.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mv *_links.csv Rawdata/Links
          git add Rawdata/Links/*
          git commit -m "Auto: add links CSV" || echo "No new links to commit"
          git push origin main

      - name: Crawl jobs
        run: python BATCH/VNWscraping/CrawlJob.py

      - name: Commit _jobs.csv
        run: |
          git add Rawdata/Jobs/*
          git commit -m "Auto: add jobs CSV" || echo "No new jobs to commit"
          git push origin main

      - name: Clean data
        run: python BATCH/VNWscraping/Clean_data.py

      - name: Commit _jobs_cleaned.csv
        run: |
          git add Cleandata/*
          git commit -m "Auto: add cleaned data CSV" || echo "No new cleaned data to commit"
          git push origin main
